name: ae_fc_error
channels:
  - conda-forge
dependencies:
  - python=3.10
  - numpy
  - scipy
  - matplotlib
  - xarray
  - netcdf4
  - pandas
  - scikit-learn
  - distributed
  - pyproj
  - jupyter
  - jupyterlab
  - cartopy
  - tensorflow
