name: censuswxindex
channels:
  - conda-forge
dependencies:
  - python=3.13.2
  - ipykernel
  - numpy
  - scipy
  - pandas
  - geopandas
  - matplotlib
  - seaborn
  - xarray
  - netCDF4
  - xagg
  - cartopy
  - scikit-learn
  - torch
  - tensorflow
  - ecmwf-api-client