name: nwp-census-eval
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.11
  - pip
  # Dev / notebooks
  - ipykernel
  # Core scientific stack
  - cartopy
  - us
  - ecmwf-api-client
  - geopandas
  - matplotlib
  - netcdf4
  - numpy
  - openpyxl
  - pandas
  - scipy
  - seaborn
  - xagg
  - xarray
  - duckdb
  - pyarrow
  # Census data
  - pip:
    - censusdis
  # Optional: ML tools
  # - scikit-learn
  # - torch
  # - tensorflow